services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ZB4N5YzA5RQaN7Vr
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local