version: '3.8'

services:
  webmin:
    image: vulhub/webmin:latest
    container_name: webmin
    restart: always
    ports:
      - "10000:10000"
    environment:
      WEBMIN_ROOT_PASSWORD: N087oo6641405M
    volumes:
      - webmin_data:/etc/webmin
      - /:/mnt/host:ro
    network_mode: host # เพื่อให้ Webmin เข้าถึงเครือข่ายโฮสต์ได้โดยตรง

  nginx-reverse-for-webmin:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # ใช้ไฟล์กำหนดค่า Nginx
    ports:
      - "80:80" # สำหรับ HTTP
      - "443:443" # สำหรับ HTTPS
    depends_on:
      - webmin

volumes:
  webmin_data: