version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/logs:/var/log/nginx  # แชร์ log (ถ้าต้องการ)
    restart: always
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge