services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000" # พอร์ตสำหรับเข้าถึง GUI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # ใช้สำหรับเชื่อมต่อ Docker Host
      - portainer_data:/data # เก็บข้อมูลของ Portainer
    environment:
      TZ: Asia/Bangkok # ตั้งค่า Timezone ตามพื้นที่ของคุณ

volumes:
  portainer_data:
